name: web_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.12.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  badges: ^2.0.3
  percent_indicator: ^4.2.2
  flutter_svg: 1.1.4
  expandable: ^5.0.1
  dropdown_button2: ^1.9.2
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5
  firebase_database: ^10.0.6
  fluttertoast: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    -
  fonts:
    - family: Poppins
      fonts:
      - asset: assets/fonts/Poppins.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
